dolittle/Runtime

Documentation/read/read_model.md
Started documentation on read models.
=> Start of the Read Model documentation

Documentation/events/domain_events.md
This tripped me up, so we should at least document it.
=> Document required convention in events

Documentation/domain_driven_design/aggregate_root.md
We didn't include this crucial part of it.
=> Document how to set state in aggregate roots

Source/Events/Relativity/BootProcedure.cs, Source/Events/Relativity/Producer/EventHorizonsConfiguration.cs, Source/Tenancy/Tenants.cs, Source/Tenancy/TenantsConfiguration.cs
=> Update EventHorizons and Tenants configuration for consistency.

Documentation/command/_index.md, Documentation/domain_driven_design/_index.md, Documentation/event_horizon/_index.md, Documentation/events/_index.md, Documentation/principles/_index.md, Documentation/read/_index.md, Documentation/resources/_index.md, Documentation/tenancy/_index.md
Added indexes with weighting to all sub folders in docs. This is a first simplistic improvement to the doc-structure. Will be doing more changes in the time to come
=> Improved menu structure in docs

Boilerplates/Application/package.json, Source/Tooling/Plugin/.gitignore, Source/Tooling/Plugin/add/AddCommand.ts, Source/Tooling/Plugin/add/AddCommandGroup.ts, Source/Tooling/Plugin/applications/ApplicationsManager.ts, Source/Tooling/Plugin/applications/IApplicationsManager.ts, Source/Tooling/Plugin/boundedContexts/BoundedContextsManager.ts, Source/Tooling/Plugin/boundedContexts/IBoundedContextsManager.ts, Source/Tooling/Plugin/create/ApplicationCommand.ts, Source/Tooling/Plugin/create/BoundedContextCommand.ts, Source/Tooling/Plugin/globals.ts, Source/Tooling/Plugin/package.json, Source/Tooling/Plugin/turnOffLogging.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1135912002182904)
=> Update plugin and boilerplates for tooling 7.*

azure-pipelines.yml
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1156980733497715)
=> Add cascades

specs.props
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1157617668651778)
=> Fixing versions for Spec/Test tooling

Documentation/overview.md
I want to get rid of the Runtime word in the future but this shall be a small landing page for now about the main concepts that are within the Runtime.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1158749437048378)
=> Add small explanation of what the runtime provides

Source/Events.Processing/FailingPartitionAlreadyExists.cs, Source/Events.Processing/FailingPartitionDoesNotExist.cs, Source/Events.Processing/IFetchEventsFromStreams.cs, Source/Events.Processing/IStreamProcessorStateRepository.cs, Source/Events.Processing/IWriteEventsToStreams.cs, Source/Events.Processing/NoEventInStreamAtPosition.cs, Source/Events.Processing/StreamProcessor.cs, Source/Events.Processing/StreamProcessorNotFound.cs, Source/Events.Store/CommittedAggregateEvent.cs, Source/Events.Store/CommittedEvent.cs, Source/Events.Store/ICommitEvents.cs, Source/Events.Store/IFetchCommittedEvents.cs, Source/Events/AggregateRoot.cs, Source/Events/AggregateRootVersion.cs, Source/Events/CommittedAggregateEvent.cs, Source/Events/CommittedEvent.cs, Source/Events/EventLogVersion.cs, Source/Events/EventWasAppliedToOtherEventSource.cs, Source/Events/FastForwardNotAllowedForStatefulAggregateRoot.cs, Specifications/Events.Processing/for_RemoteFilterProcessor/when_filtering/and_filtering_failed.cs, Specifications/Events.Processing/for_RemoteFilterProcessor/when_filtering/and_filtering_needs_retry.cs, Specifications/Events.Processing/for_RemoteFilterProcessor/when_filtering/and_filtering_succeeded.cs, Specifications/Events.Processing/for_StreamProcessor/when_stream_processor_is_processing/and_stream_has_only_one_partition/and_event_processing_failed_at_first_event.cs, Specifications/Events.Processing/for_StreamProcessor/when_stream_processor_is_processing/and_stream_has_only_one_partition/and_event_processing_failed_at_second_event.cs, Specifications/Events.Processing/for_StreamProcessor/when_stream_processor_is_processing/and_stream_has_only_one_partition/and_stream_processor_must_retry_processing_an_event_three_times.cs, Specifications/Events.Processing/in_memory_event_to_stream_writer.cs, Specifications/Events.Processing/in_memory_stream_processor_state_repository.cs
* Needed to formalize some exceptions that can get thrown in event store.
* Stream processors now process events as fast as they can, but wait 1 sec for each poll when no more events.
* Make IEventStore interfaces async
* CancellationToken on all async methods
* Get specs working
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1160966669029431)
=> Make it work after testing with MongoDB event store

Source/Events.Store.MongoDB/Events/EventHorizon/ReceivedEventExtensions.cs, Source/Events.Store/CommittedAggregateEventsExtensions.cs
Based off previous PR #346, pull that one in first.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1164049978911292)
=> Event source on grpc CommittedAggregateEvents

Source/Events.Store.MongoDB/Events/EventHorizon/ReceivedEventExtensions.cs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1163935025440402)
=> Don't change correliation on ReceivedEvent

Source/Events.Store/EventStoreService.cs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1164244301619500)
=> Fix bug in FetchForAggregate

Documentation/artifacts.md, Documentation/command/about_commands.md, Documentation/command/command_handler.md, Documentation/domain_driven_design/aggregate_root.md, Documentation/domain_driven_design/bounded_context.md, Documentation/domain_driven_design/concepts_and_value_objects.md, Documentation/events/domain_events.md, Documentation/events/event_sourcing.md, Documentation/events/event_store.md, Documentation/metrics/dynamic_metrics.md, Documentation/metrics/overview.md, Documentation/metrics/providing_metrics.md, Documentation/pipeline.md, Documentation/principles/convention_over_configuration.md, Documentation/querying_for_data.md, Documentation/read/query.md, Documentation/read/read_model.md, Documentation/resources/resources.md, Documentation/tenancy/tenancy_system.md, Documentation/tooling.md
The resturcturization will change the urls so we dont want to break all
the current links
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1164898841788993)
=> Add aliases to their current urls

Source/Events.Processing/EventProcessor.cs, Source/Events.Processing/Filters/FilterProcessor.cs, Source/Events.Store.MongoDB/EventStore.cs, Source/Events.Store/CommittedAggregateEvent.cs, Source/Events.Store/CommittedAggregateEventExtensions.cs, Source/Events.Store/CommittedAggregateEvents.cs, Source/Events.Store/CommittedAggregateEventsExtensions.cs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1164902605028148)
=> Fix aggregate

Source/Events.Store.MongoDB/EventStore.cs, Source/Events.Store/CommittedAggregateEvents.cs, Source/Events.Store/CommittedEvents.cs, Source/Events.Store/EventLogSequenceIsNotInIncrementalOrder.cs, Source/Events.Store/EventLogSequenceIsOutOfOrder.cs
This should fix @smithmx, though I have not gotten around to testing this yet...
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1166328151435947)
=> Fix committed events

Source/EventHorizon/Consumer/ConsumerClient.cs, Source/EventHorizon/Consumer/IConsumerClient.cs, Source/EventHorizon/Consumer/SubscriptionsService.cs, Source/Events.Processing/EventHandlersService.cs, Source/Events.Processing/Filters/FiltersService.cs, Source/Events.Processing/Streams/IStreamProcessors.cs, Source/Events.Processing/Streams/StreamProcessor.cs, Source/Events.Processing/Streams/StreamProcessors.cs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1168319876794588)
=> Use CancellationToken where it should

Source/Events.Processing/EventHandlers/EventHandlers.cs, Source/Events.Processing/Filters/Filters.cs
Based on this PR https://github.com/dolittle-fundamentals/DotNET.Fundamentals/pull/307/
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1170484669824960)
=> Change dispatcher method calls

Source/Events.Store.MongoDB/Events/Claim.cs, Source/Events.Store.MongoDB/Events/ClaimExtension.cs, Source/Events.Store.MongoDB/Events/ExecutionContext.cs, Source/Events.Store.MongoDB/Events/ExecutionExtensions.cs, Specifications/Events.Store.MongoDB/Events/for_ExecutionContext/when_creating.cs, Specifications/Events.Store.MongoDB/ShouldExtensions.cs, Specifications/Events.Store.MongoDB/execution_contexts.cs
Based on #407. Pull that in first
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1176675101015541)
=> Persist claims

Source/Events.Processing/Streams/ResilientStreamProcessorStateRepositoryPolicy.cs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1176788883887604)
=> Create missing policy

Source/Server/.dolittle/resources.json, Source/Server/.dolittle/tenants.json, resources.json
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1177649383496519)
=> Remove out of place tenant id

Source/Server/Server.csproj, Source/Server/Startup.cs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1177652908580716)
=> Remove reference to Dolittle.AspNetCore

Source/EventHorizon/Consumer/ConsumerClient.cs, Source/EventHorizon/Consumer/Subscriptions.cs, Source/EventHorizon/Consumer/SubscriptionsService.cs, Source/EventHorizon/Producer/ConsumerService.cs, Source/Events.Processing/EventHandlers/EventProcessor.cs, Source/Events.Processing/Filters/AbstractFilterProcessor.cs, Source/Events.Processing/Filters/EventHorizon/PublicFilterProcessor.cs, Source/Events.Processing/Filters/FilterProcessor.cs, Source/Events.Processing/Filters/FilterValidators.cs, Source/Events.Processing/Filters/Partitioned/FilterProcessor.cs, Source/Events.Processing/Streams/StreamProcessors.cs, Source/Heads/ConnectedHeads.cs, Source/Metrics/MetricsSystem.cs
Tested in triple trouble with trace level logging on, no `FormatExceptions` in the debugger.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1177839404670112)
=> Fix logging to use new format

Specifications/Events.Store/Streams/for_EventLogStreamDefinition/when_creating.cs, Specifications/Events.Store/Streams/for_StreamDefinition/when_creating/from_non_public_filter_definition.cs, Specifications/Events.Store/Streams/for_StreamDefinition/when_creating/from_public_filter_definition.cs
Added a couple of specs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1178649691649507)
=> specs for stream definitions

.github/workflows/dotnet-docker-image.yml
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1189858131593723)
=> Update 'latest' tag on docker hub when release is not prerelease

Documentation/setup_configuration.md
WIP
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1177811056688713)
=> Docs for configuration files

.github/workflows/dotnet-docker-image.yml
There was something missing in the workflow.
=> Setup docker buildx

Source/Events.Store.MongoDB/Aggregates/AggregateRoots.cs, Source/Events.Store.MongoDB/Aggregates/MultipleAggregateInstancesFound.cs, Source/Events.Store.MongoDB/Aggregates/NextAggregateRootVersionMustBeGreaterThanCurrentVersion.cs, Source/Events.Store/AggregateRootConcurrencyConflict.cs, Source/Events.Store/AggregateRootVersionIsOutOfOrder.cs, Source/Events.Store/CommittedAggregateEvents.cs, Source/Events.Store/EventWasAppliedByOtherAggregateRoot.cs, Source/Events.Store/EventWasAppliedToOtherEventSource.cs
Add more information on log exceptions (thus logging) for aggregates in the event store
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1198938031120819)
=> Add more logging for aggregates

CHANGELOG.md, Source/Events.Store.MongoDB/Aggregates/AggregateRoots.cs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1198201156703164)
=> Quick fix a bug when trying to commit aggregate events twice with expected version 0 

CHANGELOG.md, Docker/Development/Dockerfile, Source/Events.Store.MongoDB/DatabaseConnection.cs, Source/Events.Store.MongoDB/EventStoreConfiguration.cs, Source/Server/.dolittle/resources.json
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1198710468258545)
=> Add support for port in MongoDB server address, and setting MaxConnectionPoolSize (default is 100)

Documentation/Concepts/tenants.md
A simple writeup about tenants and multi-tenancy. Not quite sure what to say here tbh, maybe there isn't just a lot to say except  that multi-tenancy is a thing and we support it out of the box? I feel like a tutorial showing multi tenancy stuff would be more useful. Or maybe just having code samples here, but then we run back into the question of who owns the docs...
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1199388975490015)
=> Tenants docs

Source/EventHorizon/Consumer/EventsFromEventHorizonFetcher.cs, Source/EventHorizon/Consumer/Subscription.cs, Source/Events.Processing/Streams/AbstractScopedStreamProcessor.cs, Source/Events.Processing/Streams/CreateScopedStreamProcessors.cs, Source/Events.Processing/Streams/ICanGetTimeToRetryFor.cs, Source/Events.Processing/Streams/Partitioned/ScopedStreamProcessor.cs, Source/Events.Processing/Streams/Partitioned/TimeToRetryForPartitionedStreamProcessor.cs, Source/Events.Processing/Streams/ScopedStreamProcessor.cs, Source/Events.Processing/Streams/TimeToRetryForUnpartitionedStreamProcessor.cs, Source/Events.Store.MongoDB/Streams/StreamFetcher.cs, Source/Events.Store/Streams/ICanFetchEventsFromStream.cs
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1199575224361229)
=> Turbo kitchen missing logic

Source/Events.Processing/Streams/CreateScopedStreamProcessors.cs
Notify streams of last event processed when creating stream processors
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1199576437804536)
=> Notify when creating stream processors

Source/Events.Store/Streams/EventWaiter.cs, Source/Server/Server.csproj, Specifications/Events.Store/Streams/for_EventWaiter/when_waiting_for_10ms/and_a_later_position_is_later_notified.cs, Specifications/Events.Store/Streams/for_StreamEventWatcher/when_it_timeouts.cs
Fix event waiter by attempting to make it thread safe ++
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1199578878066125)
=> Attempt to make EventWaiter thread safe

.github/workflows/release.yml
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1199609337498654)
=> Stop pushing latest tags

CHANGELOG.md, versions.props
Fixed
* Updated the dependencies related to Grpc (v2.35.0) and protobuf
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1199657902566741)
=> Update Grpc dependencies

CHANGELOG.md
Remove unnecessary dependencies and rework some of the old fundamental parts of the code.
- `.editorconfig` for enforcing our rules and styles
- Change to .NET 5
- Change old value type classes to be `record`s to utilize the cool new C# 9 `record` type
- Fixed a bug in a logging while filtering events
- Added calls to `GC.SuppressFinalize()` in Dispose() methods as per [CA1816](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1816)
- Many "constant" properties we're missing `readonly` keyword
- Fixed many `using` statements to the new simpler form
- Uses `var`s whenever possible now
- Start using `new` statements
- Remove Concepts and Value types - replace with records
- Remove Serialisation of Concepts
- Our custom logging wrapper around Microsofts own. …
=> Remove bloat

Source/Events.Store.MongoDB/EventStore.cs, Source/Events.Store/Streams/EventWaiter.cs
A problem could occur when commiting multiple events because in regards to eventual consitency. This should likely solve that issue by notifying the event after the transaction has been committed. 
- Notify event waiter outside of the transaction
- https://app.asana.com/0/1199901627887462/1199949796334295/f
=> Fix event store eventual consistency bug

.github/workflows/runtime.yml, coverage.xml
Use dotCover to create and send code coverage report to Codacy
=> Code coverage

.github/workflows/release.yml, .github/workflows/runtime.yml, README.md, coverage.xml
Summary of the PR here. The GitHub release description is created from this comment so keep it nice and descriptive.
Remember to remove sections that you don't need or use.
- Describe the added features
- Describe the outwards facing code change
- Describe the fix and the bug
- Describe what was removed and why
- Describe the security issue and the fix
- Describe the part of the code being deprecated and why
=> Embeddings

Source/Events.Processing/EventHandlers/EventHandler.cs
Summary of the PR here. The GitHub release description is created from this comment so keep it nice and descriptive.
Remember to remove sections that you don't need or use.
- Describe the added features
- Describe the outwards facing code change
- Describe the fix and the bug
- Describe what was removed and why
- Describe the security issue and the fix
- Describe the part of the code being deprecated and why
=> cleanup-unregister-streamprocessor

Documentation/Concepts/aggregates.md, Documentation/Concepts/embeddings.md, Documentation/Concepts/event_handlers_and_filters.md, Documentation/Concepts/event_store.md, Documentation/Concepts/events.md
Changes docs about event source id
=> Change event source id

Source/Tenancy/LoggerExtensions.cs, Source/Tenancy/RuntimeServices.cs, Source/Tenancy/Tenancy.csproj, Source/Tenancy/TenantsService.cs, versions.props
Service for getting all tenants
=> Get tenants

.github/workflows/ms-teams-release.yml
Adds a workflow for notifying teams of releases
- Adds a workflow for notifying teams of releases
=> Release workflow

.github/workflows/release.yml
Fixes a problem with workflow creating github releases not triggering other workflows listening for github releases
=> Fix-workflow

.github/workflows/release.yml, .github/workflows/runtime.yml, Docker/ARM64Development/Dockerfile, Docker/ARM64Production/Dockerfile, Docker/Development/Dockerfile, Docker/Production/Dockerfile, Source/Applications.Configuration/BootProcedure.cs, Source/CLI/CLI.csproj, Source/CLI/Runtime/Aggregates/ManagementClient.cs, Source/CLI/Runtime/EventHandlers/ManagementClient.cs, Source/Server/Server.csproj, Source/Server/VersionInfo.cs, Specifications/Events.Processing/Streams/for_ScopedStreamProcessor/when_processing/and_event_processing_failed_at_first_event.cs, Specifications/Events.Processing/Streams/for_ScopedStreamProcessor/when_processing/and_event_processing_failed_at_second_event.cs, Specifications/Events.Processing/Streams/for_ScopedStreamProcessor/when_processing/and_stream_processor_must_retry_processing_an_event_three_times.cs, Specifications/Events.Processing/Streams/for_ScopedStreamProcessor/when_processing/stream_with_one_event/and_everything_is_ok.cs, Specifications/Services.Clients/for_ReverseCallClient/given/a_client/MyProtocol.cs, Specifications/Services.Clients/for_ReverseCallClient/when_connecting/and_the_server_stream_sends_2_pings_and_a_response.cs, Specifications/Services.Clients/for_ReverseCallClient/when_handling/and_connection_is_established/and_handle_is_called_multiple_times.cs, Specifications/Services.Clients/for_ReverseCallClient/when_handling/and_connection_is_established/and_the_ping_times_out.cs, Specifications/Services.Clients/for_ReverseCallClient/when_handling/and_connection_is_established/and_we_get_2_pings_and_a_request.cs, Specifications/Services.Clients/for_ReverseCallClient/when_handling/and_connection_is_established/and_we_get_a_request.cs, default.props, specs.props, versions.props
Updates the contracts to Gimli prerelease and updates the Runtime to .net 6.
=> Update to net6.0

Source/Platform/Handshake/HandshakeService.cs, Source/Platform/Handshake/Log.cs, Source/Server/Program.cs
=> Add more logging to handshake

Source/Projections.Store.Services.Grpc/ProjectionsGrpcService.cs, Specifications/Projections.Store.Services.Grpc/for_ProjectionsGrpcService/when_getting_all_in_batches/and_it_returns_10_small_states.cs, Specifications/Projections.Store.Services.Grpc/for_ProjectionsGrpcService/when_getting_all_in_batches/and_it_returns_3_medium_states.cs, Specifications/Projections.Store.Services.Grpc/for_ProjectionsGrpcService/when_getting_all_in_batches/and_it_returns_a_state_that_is_too_large.cs
Attempt to make the projection batching logic look cleaner
=> Batch cleaner

Source/Projections.Store.Services.Grpc/ProjectionsGrpcService.cs
Simplify the batch building logic so we are all happy.
=> Make it even sweeter

Source/Projections.Store.Copies.MongoDB/CannotConvertValueUsingConversion.cs, Source/Projections.Store.Copies.MongoDB/DocumentDoesNotHaveProperty.cs, Source/Projections.Store.Copies.MongoDB/IValueConverter.cs, Source/Projections.Store.Copies.MongoDB/ProjectionConverter.cs, Source/Projections.Store.Copies.MongoDB/UnknownBSONConversionType.cs, Source/Projections.Store.Copies.MongoDB/ValueConverter.cs, Source/Projections.Store.Copies.MongoDB/ValueIsNotDocument.cs, Source/Projections.Store.MongoDB/Definition/ProjectionCopyToMongoDB.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/given/a_converter_and_inputs.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/a_property_on_a_number.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/a_property_that_does_not_exist.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_multiple_conversions/on_a_complex_state.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_multiple_conversions/on_a_simple_state.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_multiple_conversions/on_objects.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_complex_state.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_simple_state/converting_some_bool.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_simple_state/converting_some_date.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_simple_state/converting_some_int.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_simple_state/converting_some_string.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_an_array.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_an_object.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/without_conversions/a_complex_state.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/without_conversions/a_simple_state.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/without_conversions/arrays.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/without_conversions/objects.cs
Implements conversions of Projection read models.
=> Implement field conversions for read models

Source/Events.Processing/Projections/ProjectionKeys.cs, Source/Events.Processing/Projections/ProjectionsProtocol.cs, Source/Projections.Store.MongoDB/Definition/ConvertProjectionDefinition.cs, Source/Projections.Store.MongoDB/Definition/ProjectionEventSelector.cs, Source/Projections.Store/Definition/OccurredFormat.cs, Source/Projections.Store/Definition/ProjectEventKeySelectorType.cs, Source/Projections.Store/Definition/ProjectionEventSelector.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/given/all_dependencies.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_occurred/and_format_is_hh.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_occurred/and_format_is_hh_mm.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_occurred/and_format_is_hh_mm_ss.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_occurred/and_format_is_invalid.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_occurred/and_format_is_yyyy.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_occurred/and_format_is_yyyy_MM.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_occurred/and_format_is_yyyy_MM_dd.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_occurred/given/an_event.cs, Specifications/Events.Processing/Projections/for_ProjectionKeys/when_type_is_static.cs, versions.props
Implement the Static and Occurred projection event key selectors
=> Implement new key selectors

Source/Events.Processing/Projections/CompareProjectionDefinitionsForAllTenants.cs
=> Add new fields to projection definition comparer

Source/CLI/CLI.csproj, Source/CLI/Runtime/ClientFactory.cs
=> Use new grpc in CLI

Docker/Development/Dockerfile, Docker/Production/Dockerfile, versions.props
Multi target build of development Dockerfile
=> Fix development dockerfile

Source/Events.Processing/Projections/ProjectionsProtocol.cs, Source/Services/InitiateReverseCallServices.cs
Reject connection when connect arguments validation failed
=> Reject connection

Source/Events.Processing/Filters/FailedFiltering.cs, Source/Events.Processing/Projections/EventProcessor.cs, Source/Events.Processing/Projections/IProjectionResult.cs, Source/Events.Processing/Projections/Projection.cs, Source/Events.Processing/Projections/ProjectionFailedResult.cs, Source/Events.Processing/Projections/ProjectionReplaceResult.cs, Source/Events.Processing/Projections/SuccessfulProjectionResult.cs
Include the retry time in projection processing results
=> Add retry for projection results

.github/workflows/release.yml, .github/workflows/runtime.yml, Docker/Development/Dockerfile, Docker/Production/Dockerfile
Setup multi arch building of docker images
=> Multi-arch

versions.props
Updates the version of the Contracts.
=> Upgrade grpc contracts versions

Source/Services/IMetricsCollector.cs, Source/Services/MetricsCollector.cs, Source/Services/ReverseCallDispatcher.cs, Source/Services/ReverseCallDispatchers.cs, Specifications/Services/for_ReverseCallDispatcher/given/a_dispatcher.cs
Adds metrics for ReverseCallDispatcher measuring the total amount of requests and request-response time
=> Metrics for ReverseCallDispatcher

Source/Aggregates.Management/Aggregates.Management.csproj, Source/Aggregates/Aggregates.csproj, Source/Embeddings.Store.Services.Grpc/Embeddings.Store.Services.Grpc.csproj, Source/Embeddings.Store.Services/Embeddings.Store.Services.csproj, Source/EventHorizon/EventHorizon.csproj, Source/Events.Management/Events.Management.csproj, Source/Events.Processing.Management/Events.Processing.Management.csproj, Source/Events.Processing/Events.Processing.csproj, Source/Events.Store.MongoDB/Events.Store.MongoDB.csproj, Source/Events.Store.Services.Grpc/Events.Store.Services.Grpc.csproj, Source/Events.Store.Services/Events.Store.Services.csproj, Source/Events/Events.csproj, Source/Projections.Store.Services.Grpc/Projections.Store.Services.Grpc.csproj, Source/Projections.Store.Services/Projections.Store.Services.csproj, Source/Resources/Resources.csproj, Source/Server/Server.csproj, Source/Services/Services.csproj, Source/Tenancy/Tenancy.csproj, Specifications/Events.Store/Events.Store.csproj, versions.props
Upgrade to the latest version of dolittle contracts
=> Upgrade to latest contracts version

Source/Events.Store.MongoDB/Persistence/IUpdateAggregateVersionsAfterCommit.cs, Source/Events.Store.MongoDB/Persistence/UpdateAggregateVersionsAfterCommit.cs, Specifications/Embeddings.Store.MongoDB/Embeddings.Store.MongoDB.csproj, Specifications/Events.Store.MongoDB/Events.Store.MongoDB.csproj, Specifications/Events.Store.MongoDB/Persistence/for_UpdateAggregateVersionsAfterCommit/and_updating_a_version_crashes.cs, Specifications/Events.Store.MongoDB/Persistence/for_UpdateAggregateVersionsAfterCommit/given/all_dependencies.cs, Specifications/Events.Store.MongoDB/Persistence/for_UpdateAggregateVersionsAfterCommit/when_commit_has/no_committed_aggregate_events.cs, Specifications/Events.Store.MongoDB/Persistence/for_UpdateAggregateVersionsAfterCommit/when_commit_has/one_commited_aggregate_events/for_one_aggregate_instance.cs, Specifications/Events.Store.MongoDB/Persistence/for_UpdateAggregateVersionsAfterCommit/when_commit_has/one_commited_aggregate_events/for_two_aggregate_instance.cs, Specifications/Events.Store.MongoDB/Persistence/for_UpdateAggregateVersionsAfterCommit/when_commit_has/two_commited_aggregate_events/for_one_aggregate_instance.cs, Specifications/Events.Store.MongoDB/Persistence/for_UpdateAggregateVersionsAfterCommit/when_commit_has/two_commited_aggregate_events/for_two_aggregate_instance.cs
Updates the aggregate versions when writing a commit
=> Update aggregates version

Source/Events.Store.MongoDB/Persistence/CommitWriter.cs, Source/Events.Store.MongoDB/Persistence/UpdateAggregateVersionsAfterCommit.cs
Actually update the aggregates versions when writing commits
=> Update aggregates versions when writing commits

.github/workflows/release.yml
This is a test to see benchmarks on release
=> Remove spaces

.github/workflows/release.yml
Correct benchmark result path in release workflow
=> Correct benchmark result path

.github/workflows/release.yml
Upload more benchmark file types to the release
=> Upload more benchmark files

Benchmarks/Events.Store/CommitAggregateEvents.cs, Benchmarks/Events.Store/CommitEvents.cs, Benchmarks/Events.Store/FetchAggregateEvents.cs
Play with some benchmark parameters
=> Play around with benchmark parameters

.github/workflows/benchmarks.yml, .github/workflows/release.yml
Extensions on benchmark result assets
=> Extensions on benchmark results

.github/workflows/benchmarks.yml, .github/workflows/release.yml, Benchmarks/Benchmarks.csproj, Benchmarks/Events.Processing/EventHandler.cs, Benchmarks/Events.Store/CommitAggregateEvents.cs, Benchmarks/Events.Store/CommitEvents.cs, Benchmarks/Events.Store/EventStoreExtensions.cs, Benchmarks/Events.Store/FetchAggregateEvents.cs, Benchmarks/JobBase.cs, Source/Events.Processing/EventHandlers/EventHandler.cs, Source/Events.Processing/EventHandlers/EventHandlerFactory.cs, Source/Events.Processing/EventHandlers/EventHandlers.cs, Source/Events.Processing/EventHandlers/EventHandlersService.cs, Source/Events.Processing/EventHandlers/EventProcessor.cs, Source/Events.Processing/EventHandlers/IEventHandler.cs, Source/Events.Processing/EventHandlers/IEventHandlerFactory.cs, Source/Events.Processing/EventHandlers/IEventHandlers.cs, Source/Events.Processing/Streams/StreamProcessor.cs, Specifications/Events.Processing/EventHandlers/for_EventHandler/given/an_event_handler.cs, Specifications/Events.Processing/EventHandlers/for_EventHandler/given/an_event_handler_with_non_writeable_target_stream.cs
=> Event handler benchmark

Benchmarks/Events.Processing/EventHandler.cs
=> Make benchmarks run faster by reducing number of events to process

.github/workflows/benchmarks.yml, .github/workflows/release.yml, Benchmarks/Events.Processing/EventHandlerFilter.cs
Benchmarks for the filter stream processor of the event handler
=> Event handler filter benchmark

.github/workflows/benchmarks.yml, .github/workflows/release.yml, Benchmarks/Events.Processing/Projection.cs, Benchmarks/JobBase.cs, Source/Events.Processing/EventHandlers/EventHandlersService.cs, Source/Events.Processing/Projections/EventProcessor.cs, Source/Events.Processing/Projections/ProjectionsService.cs
=> Projection benchmark

Benchmarks/Events.Processing/Projection.cs
Increase number of events to process in projection benchmark
=> Increase number of events for projection benchmark

.github/workflows/benchmarks.yml, .github/workflows/release.yml, Benchmarks/Events.Processing/EventHandlers/EventHandler.cs, Benchmarks/Events.Processing/EventHandlers/Filter.cs, Benchmarks/Events.Processing/Projections/Projection.cs, Benchmarks/Events.Store/Streams/StreamProcessorStateRepository.cs
Benchmarks for persisting and getting stream processor states
=> Add benchmarks for stream processor state repository

Integration/Shared/EventStoreExtensions.cs, Integration/Tests/Events.Store/given/a_clean_event_store.cs, Integration/Tests/Events.Store/should_extensions.cs, Integration/Tests/Events.Store/when_committing/an_event.cs, Integration/Tests/Events.Store/when_committing/multiple_events_in/batch.cs, Integration/Tests/Events.Store/when_committing/multiple_events_in/loop.cs, Integration/Tests/Events.Store/when_committing/multiple_events_in/parallel/batch_commits.cs, Integration/Tests/Events.Store/when_committing/multiple_events_in/parallel/single_event_commits.cs
Adds more integration tests for the event store
=> More integration tests + some restructuring

Docker/Development/Dockerfile, Docker/Production/Dockerfile
Logging formatter should now not be json
=> Fix the logging formatter name environment variable name

Source/Events.Processing/EventHandlers/Fast/ScopedFilterStreamProcessor.cs
Fixes an issue where fast processor would try to write events to stream when collection was empty
=> Only write events when there are any to write

Integration/Shared/EventStoreExtensions.cs, Integration/Tests/Events.Store/given/a_clean_event_store.cs, Integration/Tests/Events.Store/when_committing/an_event.cs, Source/Actors/Actors.csproj, Source/Actors/ContextExtensions.cs, Source/Actors/Hosting/ApplicationLifecycleHooks.cs, Source/Actors/PropsCreator.cs, Source/Events.Store/Actors/Committer.cs, Source/Events.Store/Actors/EventStore.cs, Source/Events.Store/Actors/EventStoreCouldNotBeStarted.cs, Source/Events.Store/Actors/StreamSubscriptionManagerActor.cs, Source/Events.Store/Events.Store.csproj, Source/Events.Store/ExceptionExtensions.cs, Source/Events.Store/Persistence/CommitBuilder.cs, Source/Events.Store/Persistence/CommitPipeline.cs, Source/Rudimentary/Pipelines/BatchedItem.cs, Source/Rudimentary/Pipelines/ICanAddToABatch.cs, Source/Rudimentary/Pipelines/ICanBuildABatch.cs, Source/Rudimentary/Pipelines/ICanGetNextReadyBatch.cs, Source/Rudimentary/Pipelines/IPipeline.cs, Source/Rudimentary/Pipelines/IPipelineReadyBatchAggregator.cs, Source/Rudimentary/Pipelines/Pipeline.cs, Source/Rudimentary/Pipelines/PipelineReadyBatchAggregator.cs, Source/Rudimentary/Pipelines/ReadyBatch.cs, Source/Server/Program.cs, Source/Tenancy/TenantNotConfigured.cs, Specifications/Events.Store.MongoDB/Persistence/for_UpdateAggregateVersionsAfterCommit/given/all_dependencies.cs, versions.props
Fixes an issue where Event Store would end up in an endless restarting loop when missing configuration when committing events.
- More friendly errors are logged when getting event store with missing or bad config
- Commits will get a response and not hang whenever the event store fails
=> Event store improvements

Source/Events.Store/Actors/Committer.cs
Try do self healing of aggregate root version cache in the committer actor. Do console logging for easier tracing
=> Try do aggregate root version cache self healing

Source/Events.Store/Actors/Committer.cs
=> Catch and resposnd failure

.github/workflows/release.yml, Source/Events.Store/Actors/Committer.cs
=> Committer aggregate fix

Source/Events.Store/Actors/Committer.cs
=> More info to logs

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yml, .github/workflows/release.yml, .github/workflows/runtime.yml, Docker/Development/Dockerfile, Docker/Production/Dockerfile, Runtime.sln, Source/CLI/CLI.csproj, default.props, specs.props
Upgrades the Dolittle Runtime to run on dotnet 7.
=> Dotnet 7 Runtime

Source/Events/Processing/EventHandlers/Fast/CreateScopedFilterStreamProcessors.cs, Source/Events/Store/Actors/EventLogStream.cs, Source/Events/Store/Actors/EventStore.cs, Source/Events/Store/Actors/StreamProcessorStateManager.cs
- Fixes an issue when unregistering eventstore-subscriptions. Was previously missing scopeId on the messages
=> Improvements & fixes to fast event processors

.github/workflows/release.yml, Runtime.sln, Source/CLI/Runtime/Command.cs, Source/CLI/Runtime/CommandBase.cs, Source/CLI/Runtime/Configuration/Command.cs, Source/CLI/Runtime/Configuration/CommandFailed.cs, Source/CLI/Runtime/Configuration/IManagementClient.cs, Source/CLI/Runtime/Configuration/ManagementClient.cs, Source/CLI/Runtime/Configuration/ServiceCollectionExtensions.cs, Source/CLI/Runtime/ServiceCollectionExtensions.cs, Source/Configuration.Management/Configuration.Management.csproj, Source/Configuration.Management/ConfigurationService.cs, Source/Configuration.Management/DolittleConfiguration.cs, Source/Configuration.Management/IDolittleConfiguration.cs, Source/Configuration.Management/LoggerExtensions.cs, Source/Configuration/AllConfigurations.cs, Source/Configuration/DependencyInversion/ConfigurationObjectDefinition.cs, Source/Configuration/DependencyInversion/ConfigurationObjects.cs, Source/Configuration/DependencyInversion/IAmAConfigurationObjectDefinition.cs, Source/Configuration/DependencyInversion/TenantConfigurationObjects.cs, Source/Configuration/IAllConfigurations.cs, Source/Platform/ExecutionContextCreator.cs, Source/Platform/PlatformConfiguration.cs, versions.props
Getting the current configuration of a running Runtime is useful.
- `dolittle runtime config` CLI command that gets the current running configuration.
- grpc and grpc-web api for getting the current running configuration.
=> Get current Dolittle configuration

Documentation/References/configuration.md
Updates the configuration documentation
=> Update configuration documentation

.github/workflows/release.yml, .github/workflows/runtime.yml
Cleanup
* [Disable Codacy reporting](https://github.com/dolittle/Runtime/commit/dc1b33ed3109da72f607496cd4347bdc9c645c32)
* [Clean up removed benchmark references](https://github.com/dolittle/Runtime/commit/7222635531bb34eb061e135ab6cdc9101b677018)
=> Disable codacy reporting

.github/workflows/runtime.yml, Source/Events.Store.MongoDB/CommittedEventsFetcher.cs, Source/Events.Store/Actors/Committer.cs, Source/Events.Store/Actors/EventStore.cs, Specifications/MongoDB/MongoDB.csproj, specs.props, versions.props
* Updates gRPC libraries.
* Added tolerance for removed events from main event log.
- Ability to tolerate events missing from eventlog. Before it would stop working when events were deleted. This has been changed to only logging and continuing to be able to commit new events.
=> Tolerate missing events

Source/Events/Processing/EventHandlers/Actors/TenantScopedStreamProcessorActor.cs, Source/Events/Processing/EventHandlers/Log.cs, Source/Events/Processing/Streams/Partitioned/StreamProcessorState.cs, Source/Events/Processing/Streams/StreamProcessorState.cs, Source/Events/Store/Actors/EventLogStream.cs, Source/Events/Store/Streams/IStreamProcessorState.cs
Stream processor improvements
- Reduced event log batches in-flight per subscription, reducing memory usage.
- Fixed edge case where processor would not retry old events before new events were present
- Minor fixes in stream processor state bootstrapping which affected logging.
=> Stream processor improvements

.github/workflows/benchmarks.yml, Runtime.sln, Source/Actors/Hosting/ActorSystemClusterHostedService.cs, Source/Actors/Hosting/ApplicationLifecycleHooks.cs, Source/Events.Store.MongoDB/CommittedEventsFetcher.cs, Source/Events.Store.MongoDB/Projections/AggregateEventProjection.cs, Source/Events.Store.MongoDB/Streams/Streams.cs, Source/Events/Processing/EventHandlers/Actors/TenantScopedStreamProcessorActor.cs, Source/Events/Store/Actors/EventLogStream.cs, Source/Events/Store/Actors/EventStore.proto, Source/Events/Store/Actors/EventStoreCatchupActor.cs, Source/Events/Store/Actors/StreamSubscriptionActor.cs, Source/Events/Store/Actors/SubscriptionError.cs, Source/Events/Store/Actors/SubscriptionEventsExtensions.cs, Source/Events/Store/IFetchCommittedEvents.cs, Source/Events/Store/Log.cs, Specifications/Events.Processing.Tests/Events.Processing.Tests.csproj, Specifications/Events.Processing/EventHandlers/for_EventHandler/given/all_dependencies.cs, specs.props, tests.props, versions.props
Performance focused upgrade with the following improvements:
Changed aggregate indexes to only index events produces by aggregates (partial indexes). Also included version to ensure aggregate queries do not need to drop down to collection scans. 
Also optimized aggregate queries, and ensured they do not include event horizon metadata, which is not used in the aggregate.
Rewritten event subscriptions to optimize throughput and memory usage
- Optimized catchup subscriptions
- Optimized real-time event streaming
- Ensured clean shutdown by ensuring event processing is finished before the eventstore terminates. This allows all current handlers to complete even if they need to publish new events.
=> Performance improvements

Source/Events/Processing/EventHandlers/Actors/EventHandlerProcessorActor.cs, Source/Events/Processing/Management/EventHandlers/EventHandlersService.cs
Bugfix release for the Management API (CLI). 
- Fixed bug in eventhandlers API caused by incorrect dependency passed to service
- Fixed missing response when invoking reprocessing of specific eventhandlers.
=> Management API fix

Source/Events/Store/Actors/EventLogStream.cs, Source/Events/Store/Actors/EventStoreCatchupActor.cs, Source/Events/Store/Actors/StreamSubscriptionActor.cs, Source/Events/Store/Actors/StreamSubscriptionManagerActor.cs
This release focuses on limiting maximum memory usage, while at the same time trying to stream committed events directly from memory. Each handler will now more intelligently flow from catchup / streaming mode and back based on event handler backpressure.
- Removed ability for event processors that are processing slower than events are coming in to grow in memory in an unbounded way.
=> Memory optimized event subscriptions

.editorconfig, Configurations/producer/.dolittle/runtime.yml, Integration/Benchmarks/Events.Store/CommitEvents.cs, Source/Events.Store.MongoDB/Events/AggregateMetadataExtensions.cs, Source/Events.Store.MongoDB/Events/CommittedEventExtension.cs, Source/Events.Store.MongoDB/Events/EventConverter.cs, Source/Events.Store.MongoDB/Events/EventHorizonMetadata.cs, Source/Events.Store.MongoDB/Migrations/StreamIdMatcher.cs, Source/Events.Store.MongoDB/Processing/Streams/EventHorizon/SubscriptionState.cs, Source/Events.Store.MongoDB/Processing/Streams/EventHorizon/SubscriptionStateExtensions.cs, Source/Events.Store.MongoDB/Processing/Streams/SubscriptionStateRepository.cs, Specifications/Events.Store.MongoDB.Tests/StreamIdMatcherTests.cs, Specifications/Events.Store.MongoDB/Events/for_CommittedEventExtensions/when_getting_event_horizon_metadata/from_committed_event.cs, Specifications/Events.Store.MongoDB/Events/for_EventConverter/when_converting_to_event_log_event/an_external_event.cs, Specifications/Events.Store.MongoDB/Events/for_EventConverter/when_converting_to_store_stream_event/an_external_event.cs, Specifications/Events.Store.MongoDB/event_builder.cs, Specifications/Events.Store.MongoDB/stream_event_builder.cs
Fixes and improvements to EventHorizon. 
* Fixed incorrect subscription state mapping
* Removed unused metadata from public streams
- Fixes a bug in eventhorizon state, where it incorrectly stored EventLogSequence in the position field.
=> Eventhorizon bugfix & optimizations

Integration/Benchmarks/Benchmarks.csproj, Source/DependencyInversion/AssemblyFinder.cs, Source/DependencyInversion/DependencyInversion.csproj, Source/DependencyInversion/Types/TypeScanner.cs, Source/Diagnostics/Diagnostics.csproj, Source/Diagnostics/OpenTelemetry/OpenTelemetryConfigurationExtensions.cs, Source/Events.Store.MongoDB/Events.Store.MongoDB.csproj, Source/Events/Events.csproj, Source/MongoDB/MongoDB.csproj, Source/Server/Program.cs, Source/Server/appsettings.json, specs.props, tests.props, versions.props
This is a pure maintenance release, upgrading the runtime internal dependencies to their latest stable version.
No breaking changes or interface additions had been added.
=> Maintenance release

Source/Events.Store.MongoDB/Persistence/OffsetStore.cs
This release adds offset metadata initialization on startup, and does not wait until streams are being written. This supports the sparse streams use case, allowing the runtime to work correctly with events removed from the log.
- Stream offset metadata init
=> Added initialization of offset metadata on startup for all streams

Directory.Packages.props, Source/Events.Store.MongoDB/Persistence/OffsetStore.cs
Added checks on startup for stream offset metadata, with corrections if offsets are lower than expected. 
Updated internal gRPC libraries
- Checks on already initialized stream offsets
=> Stream offset metadata initialization
