Documentation/Articles/events/event_store.md
Removed the concept of commit on the read-side of the event-store!
Not sure about event horizons - are they now commit-agnostic? As long as the event-store write-side is commit-transactional all reads *should* be able to ignore it.
=> proposed changes to event-store doc

Source/Events/EventMetadata.cs, Source/Events/EventSourceKey.cs, Source/Events/Relativity/Consumer/ParticleStreamProcessor.cs, Source/Events/Relativity/Protobuf/Conversion/EventSourceExtensions.cs, Source/Events/Store/IFetchCommittedEvents.cs, Source/Events/Store/IFetchEventSourceVersion.cs, Source/Events/VersionedEventSource.cs, Specifications/Events/Relativity/Protobuf/Conversion/for_EventSourceExtensions/when_converting_versioned_event_source_to_and_from_protobuf.cs, Specifications/Events/given/Events.cs
The EventSourceId is not a unique identifier across artifact types.  It's perfectly valid to have the same Id associated with different event source artifact types.
=> Key to an EventSource is the Id and the Artifact Type

Source/Events/Processing/BootProcedure.cs, Source/Events/Processing/ScopedEventProcessingHub.cs, Source/Events/Processing/ScopedEventProcessor.cs, Source/Events/Relativity/Consumer/ITenantOffsetRepository.cs, Specifications/Events/Processing/for_BootProcessing/when_performing_the_boot_procedure.cs
We still have Source/Tasks in runtime (Dolittle.Tasks and Dolittle.Concurrency) what do we have to do about them?
=> Use the scheduler

Source/Server/InteractionServer.cs
When listening to localhost, incoming connections from other hosts are rejected. Listening to this port accepts connections on any interface, although I believe only IPv4 addresses will work.
=> Change GRPC listening adress to listen on all interfaces.

Documentation/read/read_model.md
This code example at[ _Runtime/Overview/Read/Read Model_](https://dolittle.io/runtime/runtime/read/read_model/) doc page has the wrong `using` statement
```
using Dolittle.Read;
public class ShoppingCartPreview : IReadModel
{
public CartId Id { get {...} }
public Quantity ItemsInCart { get {...} }
public Amount Total { get {...} }
}
```
The correct import is actually `using Dolittle.ReadModels`, the example won't find the `IReadModel` interface otherwise.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1144232685447552)
=> Fix typo on using statement

Source/AggregatedPackage/Runtime.csproj, Source/Applications.Configuration/Applications.Configuration.csproj, Source/Commands.Coordination/Commands.Coordination.csproj, Source/Commands.Handling/Commands.Handling.csproj, Source/Commands.Security/Commands.Security.csproj, Source/Commands.Validation/Commands.Validation.csproj, Source/Commands/Commands.csproj, Source/Events.Migration/Events.Migration.csproj, Source/Events/Events.csproj, Source/Heads.Management/Heads.Management.csproj, Source/Heads/Heads.csproj, Source/Metrics/Metrics.csproj, Source/Microservices/Microservices.csproj, Source/Protobuf/Protobuf.csproj, Source/Queries.Coordination/Queries.Coordination.csproj, Source/Queries.Security/Queries.Security.csproj, Source/Queries.Validation/Queries.Validation.csproj, Source/Queries/Queries.csproj, Source/ReadModels/ReadModels.csproj, Source/Server/Server.csproj, Source/Tasks/Tasks.csproj, Source/Tenancy/Tenancy.csproj, Source/Transactions/Transactions.csproj, Source/Validation/Validation.csproj
First step of finally getting rid of the Git Submodule for Build
=> Changing to Dolittle.Common instead of import from submodule

Documentation/_index.md
As Runtime makes up most of the concepts found in "Building blocks" it makes sense that it takes ownership of the toplevel index file.
Also this way the github edit links are all correct for the Runtime repo, including the topmost index file (aka the one I'm adding right now)
Should be merged together with https://github.com/dolittle/Documentation/pull/68
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1164932785929085)
=> Add index file to have an overview of the building blocks section

Source/Events.Processing/Filters/RemoteFilterValidator.cs, Source/Events.Processing/Filters/TypeFilterWithEventSourcePartitionValidator.cs, Source/Events.Store.MongoDB/Streams/AbstractEventTypesFromWellKnownStreamsFetcher.cs, Source/Events.Store.MongoDB/Streams/EventTypesFromEventLogFetcher.cs, Source/Events.Store.MongoDB/Streams/EventTypesFromStreamsFetcher.cs, Source/Events.Store/Streams/IFetchEventTypesFromStreams.cs
Renamed the interface methods as well as the static overload in `EventTypesFromStreamsFetcher`. 
Multilined some method signatures also as they we're quite long.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1172181905615210)
=> Simplify IFetchEventTypesFromStreams method names

Source/Events.Store.MongoDB/Processing/Streams/StreamProcessorState.cs
The '_id' field is implicitly created by MongoDB and then with the BsonIgnoreExtraElements we can just ignore it when deserializing.
This is the smart way of dealing with the _id from https://github.com/dolittle-runtime/Runtime/pull/379
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1174066662192291)
=> Remove Id property from StreamProcessorState.

Source/Events.Store.MongoDB/Constants.cs
This way the collections are sorted nicer when viewing them in the db.
I also applied this to the `StreamProcessorStateCollection` naming.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1174258308341094)
=> Change collection names to have scopeid before other id's

Source/Server/Program.cs
This is just adding a UnhandledException Console output leveraging the AppDomain event.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1174475861437730)
=> Adding output of unhandled exceptions

Source/Events.Store.MongoDB/EventHorizon/EventHorizonEventsWriter.cs, Source/Events.Store.MongoDB/Events/EventCommitter.cs, Source/Events.Store.MongoDB/Events/EventExtensions.cs, Source/Events.Store.MongoDB/Events/EventMetadata.cs, Source/Events.Store.MongoDB/Events/StreamEventExtensions.cs, Source/Events.Store.MongoDB/Events/StreamEventMetadata.cs
Do note that as we don't yet transport the origin sequence number over grpc the `EventMetaData.OriginEventLogSequenceNumber` will be same as the events `EventLogSequenceNumber`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1175370478549746)
=> Add OriginEventLogSequenceNumber and FromEventHorizon to EventMetadata

Source/Events.Store.MongoDB/Constants.cs, Source/Events.Store.MongoDB/EventStoreConnection.cs, Source/Events.Store.MongoDB/Processing/Streams/StreamProcessorStates.cs
Removed the `GetSubscriptionStateCollection`, the new default is `GetScopedSubscriptionStateCollection` as subscription states are always scoped.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1175371654345108)
=> Remove default scoped subscription-states collection

Source/EventHorizon/Consumer/ConsumerClient.cs, Source/Events.Processing/Filters/ValidateFilterByComparingStreams.cs, Source/Events.Store.MongoDB/Events/EventExtensions.cs, Source/Events.Store.MongoDB/Events/StreamEventExtensions.cs, Source/Events.Store.MongoDB/Streams/EventFetchers.cs, Source/Events.Store/Streams/StreamEvent.cs
Also fixed the calls to the constructor, adding the correct bool depending on the context.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1175570932330942)
=> Add Partitioned property to Runtime's StreamEvents

Source/EventHorizon/Consumer/SubscriptionsService.cs, Source/Events.Store.MongoDB/Bindings.cs
There was a missing binding in `Bindings.cs` which caused Autofac to fail inside the statement:
```csharp
var subscriptionResponse = await _getConsumerClient().HandleSubscription(subscriptionId).ConfigureAwait(false);
```
This exception wasn't caught anywhere so this PR adds logging for future exceptions.
What should be the `FailureId` for the response and the message? Should the whole `subscriptionRequest` be logged in runtime?
Ref:
https://github.com/dolittle-fundamentals/DotNET.Fundamentals/pull/318
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1176011931025601)
=> Uncaught exception in SubscriptionService

Source/Events.Store.MongoDB/Processing/Streams/StreamProcessorStateDiscriminatorConvention.cs, Source/Events.Store.MongoDB/Processing/Streams/UnsupportedTypeForStreamProcessorStateDiscriminatorConvention.cs
Bug in the ThrowIfNominalTypeIsIncorrect-method. Check whether the AbstractStreamProcessorState is assignable from the nominal type.
Also use the Type.ToString in the exception message
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1177055742225598)
=> Fix stream processor state discriminator convention

Source/EventHorizon/Consumer/SubscriptionFailures.cs, Source/EventHorizon/Consumer/SubscriptionsService.cs, Source/Events.Processing/EventHandlers/EventHandlersService.cs, Source/Events.Processing/Events.Processing.csproj, Source/Events.Processing/Filters/FiltersService.cs, Source/Events.Processing/Streams/StreamProcessor.cs
We had a bug with all of the StreamProcessors not shutting down properly, causing the `EventHandlersService.Connect()` method to never end.
We never caught exceptions in the `TryGetExceptions()` call so we never
cancelled the `linkedTokenSource` meaning the code would hang forever on
the `WhenAll()`.
This PR fixes this by cancelling the `linkedTokenSource` after any of the StreamProcessors or the dispatcher finishes running.
Also adds more logging.
Added:
* More Logging
* EventHorizon SubscriptionFailures.SubscriptionCancelled FailureId
* Catch 'TaskCancelledException' when attempting to subscribe to an event horizon. This exception can occur when the subscription is cancelled by client or server before it actually manages to connect to the other runtime for the event horizon. Returns a …
=> Fix event handler cancellation

Source/Events.Store.MongoDB/Events/EventCommitter.cs
Regular committed events always had their `EventSourceId` set to an empty Guid.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1191736805436063)
=> Fix committed events getting their proper eventsourceid's set

Source/EventHorizon/Consumer/SubscriptionsService.cs
For some reason this was not passed all the way back to the Head, I assume this was just forgotten.
=> Pass EventHorizon Consent to Client when setting up a Subscription.

Documentation/Concepts/event_sourcing.md, Documentation/Concepts/event_store.md, Documentation/Concepts/events.md, Documentation/Concepts/streams.md
- Added a big ol list of the whole structure of the MongoDB implementation of the event store. Would be nice if this could be like a generated thing or we could link to our runtime c# api docs to show the classes tha build them. Alas, this is quite nice for the users for now.
- Moved commit-vs-publish line to the Event Store page from Events.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1199539487825833)
=> Event Store documentation

CHANGELOG.md, Source/Events.Store/Streams/StreamEventWatcher.cs
The debug logging was excessive as it would keep happening every 1min for every stream processor.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1199610671323804)
=> Change debug logs to trace

Source/Events.Store/CommittedAggregateEventsExtensions.cs, Source/Rudimentary/ConceptAs.cs, Specifications/Rudimentary/for_ConceptAs/when_equating.cs, Specifications/Rudimentary/for_ConceptAs/when_getting_values.cs, Specifications/Rudimentary/for_ConceptAs/when_to_stringing.cs, Specifications/Rudimentary/given/concepts.cs
Fixes a bug with our new `ConceptAs` type, that when trying to fetch nonexistent aggregate events, we would get a NullPointerException due to the implicit operator  from `ConceptAs` not checking first for `null`.
- Fix the implicit conversion on `ConceptAs` to check first if it's `null`
- Fix the `ToString()` on `ConceptAs` to check first if it's `null`
- Fix the `AggregateRootVersion` when converting `CommittedAggregateEvents` to their Protobuf representation when it was `null`
=> Fix null concept

Source/Events.Store.Services/LoggerExtensions.cs, Source/Events.Store/Streams/EventWaiter.cs, Source/Services/ReverseCallDispatcher.cs, Specifications/Events.Store/Streams/for_EventWaiter/when_trying_to_provoke_dead_lock.cs
We saw inconsistent issues while committing events in applications with event handlers that caused the runtime to deadlock when committing an event, never returning.
Inspired by this blog post https://devblogs.microsoft.com/premier-developer/the-danger-of-taskcompletionsourcet-class/ we have a theory that it might be because when a TaskCompletionSource is being waited for and SetResult is called on it then all the task's async continuations will be invoked synchronously which could lead to a deadlock scenario. If that's the case then this issue can be resolved by giving the TaskCompletionSource the TaskCreationOptions.RunContinuationsAsynchronously flag when created to force the continuations to be run asynchronously. 
~~We have yet to be able to write tests that provoke this scenario. …
=> Possible fix for deadlock issue when notifying and waiting for events

Source/Services/ReverseCalls/WrappedAsyncStreamWriter.cs
In the previous PR there was a problem with locks potentially being left locked by exceptions.
The easiest way I found to fix it was just ignore logging and metrics issues, and continue with the write as if nothing happened.
=> Fix bug in: Refactor out ping handling

Source/Services/Bindings.cs, Source/Services/HeaderRequestIdentifier.cs, Source/Services/IIdentifyRequests.cs, Specifications/Services/for_HeaderRequestIdentifier/given/MockServerCallContext.cs, Specifications/Services/for_HeaderRequestIdentifier/given/an_identifier_and_a_call_context.cs, Specifications/Services/for_HeaderRequestIdentifier/when_getting_request_id_for/and_request_does_not_have_id_header/but_has_a_binary_header.cs, Specifications/Services/for_HeaderRequestIdentifier/when_getting_request_id_for/and_request_does_not_have_id_header/multiple_times.cs, Specifications/Services/for_HeaderRequestIdentifier/when_getting_request_id_for/and_request_does_not_have_id_header/once.cs, Specifications/Services/for_HeaderRequestIdentifier/when_getting_request_id_for/and_request_has_id_header/multiple_times.cs, Specifications/Services/for_HeaderRequestIdentifier/when_getting_request_id_for/and_request_has_id_header/once.cs
Adds a little implementation that gets or generates a request id from the server call context. If it is present in X-Request-ID (case invariant matching) - that will be used, otherwise a random GUID is generated. We could use that header from the SDK in the future, and it is also the header that NGINX will set when used as a proxy.
This is to be used in the reverse call gRPC services.
=> Add request identifier for services

Source/Services/ReverseCalls/Bindings.cs, Source/Services/ReverseCalls/IMetricsCollector.cs, Source/Services/ReverseCalls/MetricsCollector.cs, Source/Services/ReverseCalls/PingedConnection.cs, Source/Services/ReverseCalls/PingedConnectionFactory.cs, Specifications/Services/ReverseCall/for_PingedConnection/given/Scenario.cs
- Used ICallbackScheduler for scheduling pings in the PingedConnection
- Created a binding for IMetricsCollector that doesn't do anything for now (we need to figure out a good metric naming strategy)
- Implemented and bound up the IKeepConnectionsAlive
There is still a lot of specs missing for PingedConnection, but we may need to get back to that...
=> Hook up pinged connection

Source/EventHorizon/Consumer/EventHorizonConnection.cs, Source/EventHorizon/Consumer/Processing/StreamProcessor.cs, Source/Events.Processing/Streams/StreamProcessor.cs, Source/Events.Processing/Streams/StreamProcessors.cs
We have issues with stream processors not being unregistered. This is an attempt to make the code more robust and correct.
=> Clean up unregistering and cancelling of stream processors

Source/Embeddings.Processing/Embedding.cs, Source/Embeddings.Processing/EmbeddingProcessor.cs, Source/Embeddings.Processing/EmbeddingProcessorFactory.cs, Source/Embeddings.Processing/StateTransitionEventsCalculator.cs, Specifications/Embeddings.Processing/for_Embedding/when_comparing/and_the_embedding_returns/an_embedding_compare_response.cs, Specifications/Embeddings.Processing/for_Embedding/when_deleting/and_the_embedding_returns/an_embedding_delete_response.cs, Specifications/Embeddings.Processing/for_StateTransitionEventsCalculator/given/all_dependencies.cs, Specifications/Embeddings.Processing/for_StateTransitionEventsCalculator/when_converging/and_desired_state_is_reached_after_one_compare.cs, Specifications/Embeddings.Processing/for_StateTransitionEventsCalculator/when_converging/and_desired_state_is_reached_after_second_compare.cs, Specifications/Embeddings.Processing/for_StateTransitionEventsCalculator/when_deleting/and_state_is_deleted_after_one_delete.cs, Specifications/Embeddings.Processing/for_StateTransitionEventsCalculator/when_deleting/and_state_is_deleted_after_second_compare.cs
The wrong event source id for uncommitted events coming from embedding was being set. The event source id to use should be the one converted from the projection key.
=> Set correct event source

Source/Services/Endpoints.cs, Specifications/Services/Services.csproj, Specifications/Services/for_Endpoints/given/default_configuration_providers.cs, Specifications/Services/for_Endpoints/given/one_service_type_with_binder.cs, Specifications/Services/for_Endpoints/given/one_service_type_with_two_binders.cs, Specifications/Services/for_Endpoints/given/two_service_types_with_different_visibility_and_two_binders_each.cs, Specifications/Services/for_Endpoints/when_starting/with_one_endpoint_enabled.cs, Specifications/Services/for_Endpoints/when_starting/with_one_endpoint_not_enabled.cs, Specifications/Services/for_Endpoints/when_starting/with_one_service_type_and_two_binders.cs, Specifications/Services/for_Endpoints/when_starting/with_two_service_types_with_different_visibility_two_binders_each.cs
Fixes the behaviour of default configuration for gRPC Endpoints. The previous implementation used default values for all endpoints together (the whole contents of the `endpoints.json` file). Meaning that if you partially specified this configuration for some endpoints, it would not use default values for the rest. This fixes that by using the default values per endpoint visibility if not provided in the config Gile.
- Use default values for each `EndpointConfiguration` per `EndpointVisibility`, instead of defaulting for the whole `EndpointsConfiguration` only when nothing was provided.
=> Use default values in endpoints configuration

Source/CLI/Runtime/Aggregates/ManagementClient.cs
Fix aggregate root version calculation when CLI converts CommittedAggregateEvents
=> Fix aggregate root version calculation when CLI converts CommittedAggregateEvents

Source/Resources/MongoDB/Bindings.cs
Fixes a problem where dependencies not following the autofac naming convention were not registered for the IoC container
=> Bind the new names to their interfaces.

Docker/ARM64Production/.dolittle/platform.json, Docker/Production/.dolittle/platform.json, Source/ApplicationModel/CustomerId.cs, Source/ApplicationModel/CustomerName.cs, Source/Platform/Handshake/HandshakeService.cs, Source/Platform/Handshake/PlatformEnvironment.cs, Source/Platform/Handshake/ResolvePlatformEnvironment.cs, Source/Platform/PlatformConfiguration.cs, Source/Rudimentary/ConceptAs.cs, Source/Server/.dolittle/platform.json, Specifications/Rudimentary/for_ConceptAs/when_to_stringing.cs
Fixes `ConceptAs.ToString()` and add new CustomerId concept for using with platform configuration. 
- `CustomerId` and `CustomerName` concepts.
- Default customer id in `platform.json` to `CustomerId.NotSet`
- Made `ConceptAs.ToString()` sealed so it is applied to all inheriting classes.
=> CustomerId and ConceptAs.ToString()

Source/Platform/Handshake/ContractsCompatibility.cs, Source/Platform/Handshake/HandshakeAttempt.cs, Source/Platform/Handshake/HandshakeFailures.cs, Source/Platform/Handshake/HandshakeService.cs, Source/Platform/Handshake/HandshakeTimeSpent.cs, Source/Platform/Handshake/IRequestConverter.cs, Source/Platform/Handshake/IVerifyContractsCompatability.cs, Source/Platform/Handshake/Log.cs, Source/Platform/Handshake/MissingHandshakeInformation.cs, Source/Platform/Handshake/Request.cs, Source/Platform/Handshake/RequestConverter.cs, Source/Platform/Handshake/RuntimeMustBeUpdated.cs, Source/Platform/Handshake/SDKIdentifier.cs, Source/Platform/Handshake/SDKMustBeUpdated.cs, Source/Platform/Handshake/VerifyContractsCompatibility.cs, Source/Server/appsettings.json, versions.props
Update Contracts to get new Handshake structure. Check that `HandshakeRequest` contains all valid information. Return new custom failures for the different situations of Handshake and version incompatibilities.
- New custom `FailureId` and `Failure`s for describing what to do when handshake fails.
- Updated Contracts
- Added a space in the log formatting config in `appsettings.json` to make it look a little nicer.
=> Upgrade Contracts, make custom failures for Handshake.

Source/Embeddings.Processing/EmbeddingProcessor.cs, Source/Embeddings.Processing/EmbeddingProcessorFactory.cs, Source/Embeddings.Processing/EmbeddingRequestWorkScheduledForWrongTenant.cs, Specifications/Embeddings.Processing/for_EmbeddingProcessor/given/all_dependencies.cs, Specifications/Embeddings.Processing/for_EmbeddingProcessor/when_deleting/and_everything_works.cs, Specifications/Embeddings.Processing/for_EmbeddingProcessor/when_deleting/and_request_is_sent_to_the_wrong_processor.cs, Specifications/Embeddings.Processing/for_EmbeddingProcessor/when_updating/and_everything_works.cs, Specifications/Embeddings.Processing/for_EmbeddingProcessor/when_updating/and_request_is_sent_to_the_wrong_processor.cs, Specifications/Services/ReverseCall/for_WrappedAsyncStreamWriter/when_writing/concurrently.cs
Fixes the problem of the ExecutionContext in the EmbeddingProcessor while processing requests by setting the TenantId of the ExecutionContext to the TenantId of the processor in the loop. The ExecutionContext is re-set in the DoWork tasks to also propagate the CorrelationId from the Client while processing requests. Also added a check that the TenantId of the ExecutionContext matches that of the processor to ensure we don't screw up somewhere else and end up with strange events committed.
- The ExecutionContext sent to the Client while processing an Embedding request was not set to the correct tenant.
=> Fix embedding execution context

Source/Events.Processing/EventHandlers/EventHandlerAlreadyRegistered.cs, Source/Events.Processing/EventHandlers/EventHandlers.cs, Source/Events.Processing/EventHandlers/EventHandlersFailures.cs, Source/Events.Processing/EventHandlers/EventHandlersService.cs, Source/Events.Processing/EventHandlers/Log.cs
Returns a known Failure when an EventHandler is registered multiple times, instead of throwing an Exception that is eaten up by gRPC. Also the incident is logged with a warning message.
=> Return failure instead of throwing exception when EventHandler is registered multiple times.

.github/workflows/release.yml, Source/Platform/Handshake/RuntimeServices.cs, Source/Platform/VersionInfo.cs, versions.props
Fix ServiceAspect descriptor for Handshake service, allow usage of `""` in VersionInfo so it will build on final release, use latest contracts, and enable macOS M1 build of CLI again.
=> Last fixes

Source/Projections.Store/Bindings.cs
Adds binding for `MetricsCollector` in `Projections.Store` so that it is properly initialised and fix the `NullReferenceException`.
=> Bind the MetricsCollector since it is not discovered.

Source/CLI/Runtime/CommandBase.cs, Source/CLI/Runtime/DockerRuntimeAddresses.cs, Source/CLI/Runtime/ICanDiscoverRuntimeAddresses.cs, Source/CLI/Runtime/ICanLocateRuntimes.cs, Source/CLI/Runtime/NamedRuntimeAddress.cs, Source/CLI/Runtime/RuntimeLocator.cs
Brings a small improvement to the "Select Runtime" list in the CLI when multiple Runtimes are found. I was playing around with it for a Docker Compose setup, and it was a bit hard to remember which ports belong to which microservice. So this PR adds a name from the containers to the list, and sorts the list so it should be a little easier to use.
=> Improve CLI Runtime selector list

Source/Events.Processing/Projections/ProjectionsProtocol.cs, Source/Projections.Store.Copies.MongoDB/MongoDBProjectionCopyStore.cs, Source/Projections.Store.Copies.MongoDB/ValueConverter.cs, Source/Projections.Store.MongoDB/Definition/ProjectionCopyToMongoDBPropertyConversion.cs, Source/Projections.Store/Definition/Copies/MongoDB/ConversionBSONType.cs, Specifications/Events.Processing/Projections/for_CompareProjectionDefinitionsForAllTenants/when_there_is_one_tenant/and_mongodb_copy_conversions_have_changed/by_adding_a_conversion.cs, Specifications/Events.Processing/Projections/for_CompareProjectionDefinitionsForAllTenants/when_there_is_one_tenant/and_mongodb_copy_conversions_have_changed/by_removing_a_conversion.cs, Specifications/Events.Processing/Projections/for_CompareProjectionDefinitionsForAllTenants/when_there_is_one_tenant/and_mongodb_copy_conversions_have_changed/conversion_type_for_nested_property.cs, Specifications/Events.Processing/Projections/for_CompareProjectionDefinitionsForAllTenants/when_there_is_one_tenant/and_mongodb_copy_conversions_have_changed/conversion_type_for_one_property.cs, Specifications/Events.Processing/Projections/for_CompareProjectionDefinitionsForAllTenants/when_there_is_one_tenant/and_mongodb_copy_conversions_have_changed/rename_to_for_nested_property.cs, Specifications/Events.Processing/Projections/for_CompareProjectionDefinitionsForAllTenants/when_there_is_one_tenant/and_mongodb_copy_conversions_have_changed/rename_to_for_one_property.cs, Specifications/Events.Processing/Projections/for_CompareProjectionDefinitionsForAllTenants/when_there_is_one_tenant/and_mongodb_copy_conversions_have_changed/should_rename_for_nested_property.cs, Specifications/Events.Processing/Projections/for_CompareProjectionDefinitionsForAllTenants/when_there_is_one_tenant/and_mongodb_copy_conversions_have_changed/should_rename_for_one_property.cs, Specifications/Projections.Store.Copies.MongoDB/for_MongoDBProjectionCopyStore/when_removing/and_deletion_is_acknowledged.cs, Specifications/Projections.Store.Copies.MongoDB/for_MongoDBProjectionCopyStore/when_removing/and_deletion_is_not_acknowledged.cs, Specifications/Projections.Store.Copies.MongoDB/for_MongoDBProjectionCopyStore/when_replacing/and_replacing_is_acknowledged.cs, Specifications/Projections.Store.Copies.MongoDB/for_MongoDBProjectionCopyStore/when_replacing/and_replacing_is_not_acknowledged.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/a_property_on_a_primitive.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/a_property_that_does_not_exist.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_multiple_conversions/on_a_complex_state.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_multiple_conversions/on_a_simple_state.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_multiple_conversions/on_objects.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_complex_state.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_simple_state/converting_some_bool.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_simple_state/converting_some_date.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_simple_state/converting_some_int.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_a_simple_state/converting_some_string.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_an_array.cs, Specifications/Projections.Store.Copies.MongoDB/for_ProjectionConverter/when_converting/with_one_conversion/on_an_object.cs, versions.props
Adds the new conversion types for projections from latest contracts, and implements the `ValueConverter` for those types. Also change persistence of conversion enum in MongoDB to string so that we can change the ordering or add new later without breaking backwards compatibility. Lastly, change the property in the copied MongoDB documents for read model copies used for the projection key from `_id` to `_dolittle_projection_key`. We might want to look at adding an index for this property later.
=> More conversions

Source/Projections.Store.Copies.MongoDB/ProjectionCopiesStorage.cs
The MongoDB driver has a lot of conversions happening behind the scenes with BsonBinaryData that represents Guids. By setting it to Unspecified in the client settings, it seems to respect the exact type that the ValueConverter decides.
=> Set GuidRepresentation for the MongoDB copy storage to Unspecified

Source/CLI/CLI.csproj
Add the gRPC M1 Contrib package to the CLI so that it can run on Apple M1 chips.
=> Add the M1 contrib package to the CLI

Documentation/References/configuration.md
Updates the documentation for `dolittle.io` about the Runtime configuration to include the `readModels` configuration in the section about `resources.json`.
=> Update description of Runtime resources config to include readmodels

Source/Events.Processing/Filters/AbstractFilterProcessor.cs, Source/Events.Processing/Filters/Log.cs, Specifications/Events.Processing/Filters/for_AbstractFilterProcessor/when_processing/and_filtering_failed.cs, Specifications/Events.Processing/Filters/for_AbstractFilterProcessor/when_processing/and_writing_filtered_event_fails.cs
When AbstractFilterProcessor handles a failed filtering result it logs that it failed filtering. Also catches exceptions when trying to write to the filtered stream, so that it is handled the same way as any other event processing failure.
=> When filter result is failed it should log it

Source/EventHorizon/Consumer/Processing/EventsFromEventHorizonFetcher.cs, Source/EventHorizon/Producer/EventHorizon.cs, Source/Events.Store.MongoDB/Streams/StreamFetcher.cs, Source/Events.Store/Streams/ICanFetchEventsFromStream.cs
Fixes an issue introduced many versions ago related to event horizon producer non-stop polling the event store for an event that isn't there
=> Hinder event horizon from polling the event store

Integration/Tests/Events.Processing/EventHandlers/given/single_tenant_and_event_handlers.cs, Source/Events.Processing/Filters/ValidateFilterByComparingStreams.cs, Source/Events.Store.MongoDB/Events.Store.MongoDB.csproj, Source/Events.Store.MongoDB/Streams/StreamFetcher.cs, Source/Events.Store/Streams/ICanFetchRangeOfEventsFromStream.cs, Specifications/Events.Processing/Filters/for_ValidateFilterByComparingStreams/given/all_dependencies.cs, Specifications/Events.Processing/Filters/for_ValidateFilterByComparingStreams/when_validating/and_fetching_the_old_stream_events_fails.cs, Specifications/Events.Processing/Filters/for_ValidateFilterByComparingStreams/when_validating/and_fetching_the_source_stream_events_fails.cs
The filter validator for public filters would take the whole event log into memory and compare filtered streams in memory. This could cause OutOfMemoryException if the event log is big enough
- Fixes `OutOfMemoryException` caused by filter validator for public filters.
=> Fixes OutOfMemoryException during public filter validation

Source/Embeddings.Processing/EmbeddingsService.cs, Source/EventHorizon/Consumer/Processing/Log.cs, Source/EventHorizon/Producer/EventHorizon.cs, Source/Events.Processing/EventHandlers/EventHandlersService.cs, Source/Events.Processing/Filters/FiltersService.cs, Source/Events.Processing/Projections/ProjectionsService.cs, Source/Events.Processing/Streams/Log.cs, Source/Services/InitiateReverseCallServices.cs, Specifications/Embeddings.Processing/for_EmbeddingsService/when_connecting/and_an_embedding_processor_is_already_registered.cs
- Log warning instead of debug when event store is unavailable
- Dispose correctly of reverse call dispatcher
=> Properly dispose reverse call dispatcher

.github/workflows/compatibility-table-update.yml, Documentation/References/compatibility.md, Documentation/merge-compatibility-table-template.sh
Adds a workflow and a script that is used together to run the `dolittle/contracts-compatibility' tool recalculate a fresh Runtime <-> SDK compatibility table and merge it into the existing one. If there is an update to the file, this will be committed and pushed to the default branch.
The workflow is setup to run every morning, and can be triggered manually on GitHub.
=> Cron update table

Integration/Shared/Runtime.cs, Integration/Tests/Events.Store/when_writing_to_stream/that_is_not_scoped/when_writing_to_stream.cs, Integration/Tests/Events.Store/when_writing_to_stream/that_is_scoped/when_writing_to_stream.cs, Source/Events.Store.MongoDB/Streams/EventsToStreamsWriter.cs
Fixes a bug in the implementation of handling multiple writes of the same events to a stream (https://github.com/dolittle/Runtime/pull/704). The previous fix did not catch the case where a single event was written multiple times - which is the case for most writes, e.g. when using Event Handlers.
- The `EventsToStreamsWriter.WriteOnlyNewEvents` failed when it was given a single event because it throws a `MongoWriteException` instead of a `MongoBulkWriteException`
=> Fix bug in handling of multiple writes of same event to stream.

Source/Events.Processing/Streams/AbstractScopedStreamProcessor.cs
- Fixes a minor memory leak for scoped stream processors
=> Fixes a mem leak in AbstractScopedStreamProcessor

Source/Aggregates.Management/AggregateRootsService.cs, Source/DependencyInversion/Attributes/ServicesBuilderForTypesWith.cs, Source/DependencyInversion/Attributes/TenantServicesBuilderForTypesWith.cs, Source/DependencyInversion/Types/TypeAttributeExtensions.cs, Source/Events.Management/EventTypesService.cs, Source/Events.Processing.Management/EventHandlers/EventHandlersService.cs, Source/Events.Processing.Management/Projections/ProjectionsService.cs, Source/Server/Program.cs, Source/Services/Configuration/EndpointsConfiguration.cs, Source/Services/EndpointVisibility.cs, Source/Services/Hosting/HostBuilderExtensions.cs, Source/Services/Hosting/KestrelConfiguration.cs, Source/Services/Hosting/ManagementWebServiceAttribute.cs, Source/Services/Hosting/ServiceCollectionExtensions.cs, Source/Services/Services.csproj, versions.props
Exposing management services on a new, configurable, grpc-web port so that we can make calls to the management services from a web browser
- Endpoint configuration for managementWeb with default port 51152
- Exposing management services through grpc-web
=> Add gRPC-web Management service endpoint

Source/Events.Processing/Streams/Partitioned/FailingPartitions.cs
Fixes a bug in the partitioned stream processing that could cause partitioned event handlers that were failing to be called with big retry processing attempts number which would in turn cause the SDK to wait for the maximum amount of time (usually 1 minute) 
- Partitioned stream processing retry processing attempts calculation bug
=> Fix a bug where the retry processing attempts could be uint max

Source/Events.Processing/EventHandlers/Fast/CreateScopedFilterStreamProcessors.cs, Source/Events.Store/Actors/EventLogStream.cs
- Fixes correct unregistering of eventlog streams. Was only possible to trigger with fast event handlers enabled, which consumes the stream directly.
=> Fixes unregistering eventlogstream, passing scope in request

Docker/Production/.dolittle/platform.yml, Docker/Production/Dockerfile
Don't include a platform config with Production environment in production docker image.It ended up overwriting the environment for all Runtimes
=> Remove platform configuration from production image

Integration/Benchmarks/Events.Processing/EventHandlers/EventHandler.cs, Integration/Tests/Events.Processing/EventHandlers/given/single_tenant_and_event_handlers.cs, Source/Events.Store.MongoDB/Streams/StreamFetcher.cs, Source/Events/ActorPropsAdder.cs, Source/Events/InternalsVisibleTo.cs, Source/Events/Processing/EventHandlers/Actors/ActorEventHandler.cs, Source/Events/Processing/EventHandlers/Actors/ConcurrentPartitionedProcessor.cs, Source/Events/Processing/EventHandlers/Actors/EventHandlerProcessorActor.cs, Source/Events/Processing/EventHandlers/Actors/NonPartitionedProcessor.cs, Source/Events/Processing/EventHandlers/Actors/PartitionedProcessor.cs, Source/Events/Processing/EventHandlers/Actors/ProcessorBase.cs, Source/Events/Processing/EventHandlers/Actors/TenantScopedStreamProcessorActor.cs, Source/Events/Processing/EventHandlers/EventHandlerInfo.cs, Source/Events/Processing/EventHandlers/EventHandlerRegistrationArguments.cs, Source/Events/Processing/EventHandlers/EventHandlersProtocol.cs, Source/Events/Processing/Streams/Partitioned/StreamProcessorState.cs, Source/Events/Store/Streams/ICanFetchEventsFromPartitionedStream.cs, Specifications/Events.Processing.Tests/concurrent/ConcurrentPartitionedProcessorTests.cs, Specifications/Events.Processing/EventHandlers/for_EventHandler/given/all_dependencies.cs, versions.props
Adds support for a new mode to run partitioned event handlers in. With concurrency > 1, event handlers are able to process each partition (eventsourceId) in parallel. This greatly improves throughput, but requires the handlers to be thread safe and not require global ordering of events. Each partition still has full ordering guarantees and will be processed sequentially.
=> Concurrent processing support for event handlers

Source/EventHorizon/EventHorizonGlobalSettings.cs, Source/EventHorizon/Producer/ConsumerService.cs, Source/Events.Store/EventHorizon/ConsentId.cs
Added the ability to not require producer consent when consuming from event horizon.
To disable required consent, use the following configuration: `DOLITTLE__RUNTIME__EVENTHORIZON__REQUIRECONSENT=false`
This will then pass NoConsent (empty guid) as a valid consent for the consumer, and allow it to consume as normal.
=> Add option to not require producer consent when consuming from EventHorizon

Source/EventHorizon/Consumer/Processing/EventsFromEventHorizonFetcher.cs, Source/Events.Store.MongoDB/CommittedEventsFetcher.cs, Source/Events.Store.MongoDB/Development/MongoDB/README.md, Source/Events.Store.MongoDB/Streams/EventFetchers.cs, Source/Events.Store.MongoDB/Streams/StreamFetcher.cs, Source/Events/Processing/Management/EventHandlers/EventHandlersService.cs, Source/Events/Store/IFetchCommittedEvents.cs, Source/Events/Store/Streams/ICanFetchEventsFromStream.cs, Source/Events/Store/Streams/Legacy/EventLogSequenceFromStreamPosition.cs, Source/Events/Store/Streams/Legacy/IGetEventLogSequenceFromStreamPosition.cs, Source/Events/Store/Streams/Legacy/StreamPositionToEventLogPositionService.cs
Rewritten GetEventLogPosition which maps from legacy stream positions to the event log sequence. Will now retrieve the correct offset from the stream used in V8.
Also changed the logic to get the next stream position to use the last element instead of the count.
Continuing from a specific stream position will now use the eventlog position for the processor instead of the stream position.
=> Change stream position logic to align with eventlog instead of stream.

.github/workflows/benchmarks.yml, Integration/Tests/Events.Processing/given/a_clean_event_store.cs, Source/Events.Store.MongoDB/Streams/StreamFetcher.cs, Source/Events/Processing/EventHandlers/Actors/ConcurrentPartitionedProcessor.cs, Source/Events/Processing/EventHandlers/Actors/EventHandlerProcessorActor.cs, Source/Events/Processing/EventHandlers/Actors/NonPartitionedProcessor.cs, Source/Events/Processing/EventHandlers/Actors/PartitionedProcessor.cs, Source/Events/Processing/EventHandlers/Actors/ProcessorBase.cs, Source/Events/Processing/EventHandlers/Actors/TenantScopedStreamProcessorActor.cs, Source/Events/Processing/EventHandlers/EventHandlerFactory.cs, Source/Events/Processing/EventHandlers/EventHandlersProtocol.cs, Source/Events/Processing/EventHandlers/EventProcessor.cs, Source/Events/Processing/EventHandlers/LoggerExtensions.cs, Source/Events/Processing/Filters/AbstractFilterProcessor.cs, Source/Events/Processing/IEventProcessor.cs, Source/Events/Store/Actors/EventLogStream.cs, Source/Events/Store/Actors/StreamSubscriptionActor.cs, Source/Events/Store/Log.cs, Source/Events/Store/Streams/StreamEventSubscriber.cs, Source/Projections.Store.MongoDB/State/ProjectionStates.cs, Source/Services/Actors/ReverseCallDispatcherActor.cs, Source/Services/IConvertReverseCallMessages.cs, Source/Services/IReverseCallDispatcher.cs, Source/Services/InitiateDisconnect.cs, Source/Services/Log.cs, Source/Services/ReverseCallDispatcher.cs, Specifications/Events.Processing/Mappings/streamprocessorstate/partitioned/failing/mapping_is_correct.cs, versions.props
Adds graceful disconnects for event handlers. This ensures that the system waits for the current handlers to complete before completing shutdowns / disconnects.
Also adresses some minor internal fixes.
- Updated projections to accommodate newer MongoDB drivers.
- Rewritten event handlers to support graceful disconnects from the client.
- Resolved an issue in eventlogstream-subscriptions, ensuring correct subscription cancellation.
=> Graceful disconnect

Source/Actors/Hosting/ApplicationLifecycleHooks.cs, Source/Events/Processing/EventHandlers/Actors/ActorEventHandler.cs, Source/Events/Processing/EventHandlers/Actors/ActorSystemExtensions.cs, Source/Events/Processing/EventHandlers/Actors/EventHandlerProcessorActor.cs, Source/Events/Processing/EventHandlers/Actors/TenantScopedStreamProcessorActor.cs, Source/Events/Processing/EventHandlers/EventHandlerFactory.cs, Source/Events/Processing/EventHandlers/LoggerExtensions.cs, Specifications/Events.Processing/EventHandlers/for_EventHandler/given/all_dependencies.cs
Adds shutdown hooks to active eventhandlers, ensuring that there are no requests in-flight when the runtime stops.
=> Improve runtime termination procedure

Integration/Shared/Runtime.cs, Integration/Tests/Events.Processing/EventHandlers/given/single_tenant_and_event_handlers.cs, Source/EventHorizon/Consumer/Processing/EventProcessor.cs, Source/Events.Store.MongoDB/CommittedEventsFetcher.cs, Source/Events.Store.MongoDB/DatabaseConnection.cs, Source/Events.Store.MongoDB/Streams/EventsToStreamsWriter.cs, Source/Events/Store/Log.cs, Source/Events/Store/Streams/Legacy/EventLogSequenceFromStreamPosition.cs, Specifications/Events.Processing/Mappings/streamprocessorstate/partitioned/failing/mapping_is_correct.cs
Fixes issue where an EventHorizon event could be skipped by race condition between tenants. 
- Removed incorrectly ignored exception in EventHorizon.
- Classify write conflict as duplicate key.
=> Eventhorizon error handling

Integration/Tests/Events.Processing/EventHandlers/given/single_tenant_and_event_handlers.cs, Source/Actors/Hosting/HostBuilderExtensions.cs, Source/Configuration/Parsing/ConfigurationParser.cs, Source/Diagnostics/Diagnostics.csproj, Source/Events.Store.MongoDB/DatabaseConnection.cs, Source/Events.Store.MongoDB/EventStoreConfiguration.cs, Source/Projections.Store.MongoDB/DatabaseConnection.cs, Source/Projections.Store.MongoDB/ProjectionsConfiguration.cs, Source/Resources/MongoDB/ConnectionStringFromResourceConfiguration.cs, Source/Resources/MongoDB/MongoDBConfiguration.cs, Source/Server/.dolittle/runtime.yml, versions.props
Changed MongoDB configuration to support srv connection strings. This allows the runtime to use any cloud hosted MongoDB services, such as Atlas.
This is backwards compatible with old connection format, and does not require changing config for existing deployments.
In addition to this, internal dependencies have been upgraded as well.
- "connectionString" configuration for MongoDB
=> Add MongoDB Atlas support

Integration/Tests/Events.Store/should_extensions.cs, Source/Bootstrap/BoostrapProcedures.cs, Source/Bootstrap/ICanPerformBoostrapProcedure.cs, Source/Events.Store.MongoDB/DatabaseMigrator.cs, Source/Events.Store.MongoDB/Events/Event.cs, Source/Events.Store.MongoDB/Events/EventConverter.cs, Source/Events.Store.MongoDB/Events/StreamEvent.cs, Source/Events.Store.MongoDB/Persistence/ConvertCommitToEvents.cs, Source/Events.Store.MongoDB/StreamIdMatcher.cs, Source/Events.Store.MongoDB/Streams/Streams.cs, Source/Events/Store/Actors/BootstrapProcedures.cs, Source/Events/Store/Actors/IMetricsCollector.cs, Source/Events/Store/Actors/MetricsCollector.cs, Source/Events/Store/Actors/StreamSubscriptionActor.cs, Specifications/Events.Store.MongoDB/Events/for_EventConverter/when_converting_to_event_log_event/an_external_event.cs, Specifications/Events.Store.MongoDB/Events/for_EventConverter/when_converting_to_store_stream_event/a_non_aggregate_event.cs, Specifications/Events.Store.MongoDB/Events/for_EventConverter/when_converting_to_store_stream_event/an_aggregate_event.cs, Specifications/Events.Store.MongoDB/Events/for_EventConverter/when_converting_to_store_stream_event/an_external_event.cs, Specifications/Rudimentary/for_TaskGroup/when_both_tasks_fail.cs
This release optimizes how events are stored in MongoDB, by only including relevant metadata for the events. This means that only events produced by aggregates will store aggregate metadata, and event horizon metadata is excluded for normal events. 
In addition, this adds metrics to stream subscriptions showing how many events are streamed / buffered directly from commits, and how many are done as catch-up events via the database.
- Metric `dolittle_customer_runtime_events_store_streamed_events_total`
- Metric `dolittle_customer_runtime_events_store_catchup_events_total`
- For non-aggregate events: Removed `Aggregate` object from MongoDB
- For non-EventHorizon events: Removed `EventhorizonMetadata` object from MongoDB
=> Optimized MongoDB event storage

Source/Events.Store.MongoDB/Migrations/V6EventSourceMigrator.cs, Source/Events.Store.MongoDB/Migrations/V9Migrations.cs
The runtime performs some housekeeping tasks when starting after being upgraded from an older version. Since the runtime has a compatibility layer supporting the older database formats, it is possible to process and commit events while the migration is being performed. 
This changes the behavior from 9.3.1, where the runtime would wait for the migrations to complete before starting.
- Allow migrations to be performed in the background
- Parallelized migrations.
=> Moved DB-optimizations & migrations to background tasks.

Source/Events/Store/Actors/StreamSubscriptionActor.cs, Source/Events/Store/Streams/StreamEventSubscriber.cs
Fixes an issue where the runtime could use large amounts of memory when reprocessing. Also tuned the pipeline to use slightly less memory overall.
- Ensured that the stream processor subscriptions do not request loading additional events unless the pipeline has < 2 un-acknowledged batches.
=> Fix: Improve memory usage when reprocessing

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yml, .github/workflows/release.yml, .github/workflows/runtime.yml, Docker/Development/Dockerfile, Docker/Production/Dockerfile, Source/CLI/CLI.csproj, Source/Events.Store.MongoDB/Development/MongoDB/Dockerfile, default.props, specs.props, tests.props
Upgrades the production image of the runtime to use .NET 8, with the performance improvements this brings.
The development image is still on 7, keeping the bundled MongoDB as is.
=> .NET 8 hosting

Source/Events.Store.MongoDB/CommittedEventsFetcher.cs, Source/Events.Store.MongoDB/Streams/StreamFetcher.cs
Fixed stream ordering when using  DB's that do not use the natural sort order of _id. This has been proven to be a potential issue on MongoDB Atlas.
- Added explicit sorting on _id when querying streams
=> Atlas stream order fix

Configurations/compose/docker-compose.yml, Configurations/consumer/.dolittle/runtime.yml, Configurations/producer/.dolittle/runtime.yml, Integration/Shared/Runtime.cs, Integration/Tests/Events.Store/when_writing_to_stream/that_is_not_scoped/when_writing_to_stream.cs, Integration/Tests/Events.Store/when_writing_to_stream/that_is_scoped/when_writing_to_stream.cs, Source/Events.Store.MongoDB/Events/Event.cs, Source/Events.Store.MongoDB/Events/IEvent.cs, Source/Events.Store.MongoDB/Events/StreamEvent.cs, Source/Events.Store.MongoDB/Streams/EventsToStreamsWriter.cs, Source/Events.Store.MongoDB/Streams/IWriteEventsToStreamCollection.cs, Source/Events/Processing/EventLogSequenceAlreadyWritten.cs, Source/Events/Processing/Filters/AbstractFilterProcessor.cs, Source/Server/Web/WebServerConfiguration.cs
Hardened the handling of already written stream events. Will now log and skip in filter processors. Previously it was able to get stuck while processing a filter that was in an inconsistent state.
- Improved error handling for filter processors, allowing the runtime to self-correct when the stream and processor state does not match
=> Filter processor self-correction

Source/Events.Store.MongoDB/EventHorizon/EventHorizonEventsWriter.cs, Source/Events.Store.MongoDB/Persistence/CommitWriter.cs, Source/Events.Store.MongoDB/Persistence/OffsetStore.cs, Source/Events.Store.MongoDB/Persistence/RedactionUtil.cs, Source/Events.Store.MongoDB/Streams/Streams.cs, Source/Events/Store/Actors/EventStore.cs, Source/Events/Store/Persistence/Commit.cs, Source/Events/Store/Persistence/CommitBuilder.cs, Source/Events/Store/Redactions/Redaction.cs
Runtime support for [GDPR redactions](https://github.com/dolittle/DotNET.SDK/releases/tag/v23.5.0). This adds support for redacting personal data from previously committed events.
Redactions are scoped to a single artifact-type (EventTypeId) and an EventSourceId. 
It will recognize events with the correct GUID prefix `"de1e7e17-bad5-da7a"` that match the event payload and is valid.
```csharp
public class Event
{
public required string EventId { get; init; }
public required string EventAlias { get; init; }
/// <summary>
/// The properties that will be redacted, and the replacement values.
/// Can be null, in which case the properties will be redacted with a default value
/// </summary>
public required Dictionary<string, object?> RedactedProperties { get; init; }
public required string …
```
=> GDPR redaction support
